# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "TFAdemo"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: template_flute

# template: "template_toolkit"
# engines:
#   template:
#     template_toolkit:
#       start_tag: '<%'
#       end_tag:   '%>'

session: YAML

engines:
  session:
    YAML:
      cookie_name: eshop.session
      is_secure: 1
      is_http_only: 1

plugins:
  Auth::Extensible:
    realms:
      users:
        provider: Demo
        username_key_name: user
        users:
           - user: marco
             pass: zzecret

behind_proxy: 1

title: "Two-Factor Authentication Demo"
